'use client';

import { parseISO } from 'date-fns';

import { v4 as uuidv4 } from 'uuid';
import type { BreadOrder, CartItem, BreadOrderWithCustomer } from '@/lib/types';
import { db } from '@/lib/db';
import { salesService } from './sales.service';
import { BREAD_WEEK_DAYS } from '@/lib/constants';
import { useAppStore } from '@/stores/appStore';

const triggerSync = () => {
    if (typeof window !== 'undefined') {
        const state = useAppStore.getState();
        if (state && state.actions) {
            state.actions.triggerSmartSync();
        }
    }
};

class BreadService {

    async generateAndGetOrdersForDate(
        date: string,
    ): Promise<BreadOrderWithCustomer[]> {
        const activeBreadClientsCount = await db.customers
            .where('isBreadClient')
            .equals(true)
            .count();

        const autoGeneratedCount = await db.bread_orders
            .where('date')
            .equals(date)
            .and(o => o.customerUuid !== null && !o.isManual)
            .count();

        if (activeBreadClientsCount > 0 && autoGeneratedCount === 0) {
            await this.createDayOrders(date);
        }

        const orders = await db.bread_orders
            .where('date')
            .equals(date)
            .sortBy('createdAt');

        const customerUuids = Array.from(
            new Set(orders.map(o => o.customerUuid).filter(Boolean) as string[]),
        );
        const customers =
            customerUuids.length > 0
                ? await db.customers
                      .where('uuid')
                      .anyOf(customerUuids)
                      .toArray()
                : [];
        const customerMap = new Map(customers.map(c => [c.uuid, c]));

        return orders.map(o => ({
            ...o,
            customer: o.customerUuid
                ? customerMap.get(o.customerUuid) || null
                : null,
        }));
    }

    private async createDayOrders(date: string): Promise<void> {
        // FIX: Use parseISO from date-fns — new Date(string) is timezone-unsafe
        const dayIndex = parseISO(date).getDay();
        const dayOfWeek = BREAD_WEEK_DAYS[dayIndex];

        const activeBreadClients = await db.customers
            .where('isBreadClient')
            .equals(true)
            .toArray();

        const ordersToCreate: BreadOrder[] = [];

        for (const client of activeBreadClients) {
            if (client.bread_type_recurrence === 'aucun') continue;

            let quantity = 0;
            if (client.bread_type_recurrence === 'quotidien') {
                quantity = client.bread_quantite_defaut || 0;
            } else if (
                client.bread_type_recurrence === 'jours_specifiques' &&
                client.bread_jours_semaine?.[dayOfWeek]?.actif
            ) {
                quantity = client.bread_jours_semaine[dayOfWeek].quantite || 0;
            }

            if (quantity > 0) {
                ordersToCreate.push({
                    uuid:       uuidv4(),
                    customerUuid: client.uuid,
                    date,
                    quantite:   quantity,
                    isManual:   false,
                    est_paye:   false,
                    est_livre:  false,
                    venteUuid:  null,
                    createdAt:  new Date(),
                    updatedAt:  new Date(),
                });
            }
        }

        if (ordersToCreate.length > 0) {
            // FIX: Use transaction to prevent duplicate order generation race condition
            // (e.g. two browser tabs opening the bread page at the same time)
            await db.transaction('rw', [db.bread_orders], async () => {
                const existingCount = await db.bread_orders
                    .where('date').equals(date)
                    .and(o => o.customerUuid !== null && !o.isManual)
                    .count();
                if (existingCount === 0) {
                    await db.bread_orders.bulkAdd(ordersToCreate);
                }
            });
            triggerSync();
        }
    }

    async addManualBreadOrder(params: {
        customerUuid?: string;
        customName?: string;
        date: string;
        quantity: number;
    }): Promise<BreadOrder> {
        const { customerUuid, customName, date, quantity } = params;

        if (customerUuid) {
            const existingOrder = await db.bread_orders
                .where({ customerUuid, date })
                .first();
            if (existingOrder) {
                throw new Error(
                    'Une commande existe déjà pour ce client à cette date.',
                );
            }
        }

        const newOrder: BreadOrder = {
            uuid:         uuidv4(),
            customerUuid: customerUuid || null,
            customName:   customName || undefined,
            date,
            quantite:     quantity,
            isManual:     true,
            est_paye:     false,
            est_livre:    false,
            venteUuid:    null,
            createdAt:    new Date(),
            updatedAt:    new Date(),
        };

        await db.bread_orders.add(newOrder);
        triggerSync();
        return newOrder;
    }

    async updateBreadOrderQuantity(
        uuid: string,
        quantity: number,
    ): Promise<void> {
        const order = await db.bread_orders.where('uuid').equals(uuid).first();
        if (!order || order.venteUuid) return;

        const updateData: Partial<BreadOrder> = {
            quantite:   quantity,
            updatedAt:  new Date(),
        };
        if (order.quantite_origine === undefined) {
            updateData.quantite_origine = order.quantite;
        }
        await db.bread_orders.update(order.id!, updateData);
        triggerSync();
    }

    async updateBreadOrderDeliveryStatus(
        uuid: string,
        delivered: boolean,
    ): Promise<void> {
        const order = await db.bread_orders.where('uuid').equals(uuid).first();
        if (!order) return;
        await db.bread_orders.update(order.id!, {
            est_livre: delivered,
            updatedAt: new Date(),
        });
        triggerSync();
    }

    async deleteBreadOrder(uuid: string): Promise<void> {
        const order = await db.bread_orders.where('uuid').equals(uuid).first();
        if (order && !order.venteUuid) {
            await db.bread_orders.delete(order.id!);
            triggerSync();
        }
    }

    async convertBreadOrdersToSales(
        orderUuids: string[],
        breadPrice: number,
    ): Promise<void> {
        await db.transaction(
            'rw',
            [
                db.bread_orders,
                db.sales,
                db.products,
                db.inventory_logs,
                db.customers,
                db.payments,
                db.product_returns,
                db.company_profile
            ],
            async () => {
                const orders = await db.bread_orders
                    .where('uuid')
                    .anyOf(orderUuids)
                    .toArray();
                const filteredOrders = orders.filter(o => !o.venteUuid);
                if (filteredOrders.length === 0) return;

                const groupedOrders = new Map<string, BreadOrder[]>();
                filteredOrders.forEach(order => {
                    const key = order.customerUuid || `unreg-${order.uuid}`;
                    if (!groupedOrders.has(key)) groupedOrders.set(key, []);
                    groupedOrders.get(key)!.push(order);
                });

                for (const [, customerOrders] of Array.from(groupedOrders.entries())) {
                    const totalQuantity = customerOrders.reduce(
                        (sum, o) => sum + o.quantite,
                        0,
                    );
                    if (totalQuantity <= 0) continue;

                    const firstOrder = customerOrders[0];
                    const displayName = firstOrder.customName || 'Pain';

                    const breadCartItem: CartItem = {
                        uuid:         'BREAD_PRODUCT',
                        name:         displayName,
                        price:        breadPrice,
                        purchasePrice: 0,
                        quantity:     Infinity,
                        cartQuantity: totalQuantity,
                        minStockLevel: 0,
                    };

                    const sale = await salesService.createSale({
                        items:         [breadCartItem],
                        discountType:  'fixed',
                        discountValue: 0,
                        amountPaid:    0,
                        customerUuid:  firstOrder.customerUuid,
                    });

                    const orderIds = customerOrders.map(o => o.id!);
                    await db.bread_orders
                        .where('id')
                        .anyOf(orderIds)
                        .modify({
                            venteUuid: sale.uuid,
                            est_paye:  true,
                            est_livre: true,
                            updatedAt: new Date(),
                        });
                }
            },
        );

        triggerSync();
    }

    async billAllRemainingOrdersForDate(
        date: string,
        breadPrice: number,
    ): Promise<number> {
        const unpaidOrders = await db.bread_orders
            .where('date')
            .equals(date)
            .and(o => !o.venteUuid && o.quantite > 0)
            .toArray();

        if (unpaidOrders.length === 0) return 0;

        const uuids = unpaidOrders.map(o => o.uuid);
        await this.convertBreadOrdersToSales(uuids, breadPrice);
        return unpaidOrders.length;
    }
}

export const breadService = new BreadService();
